const API = '/api/api_rondas_vigilante.php';
const params = new URLSearchParams(window.location.search);
const token = String(params.get('token') || '').toLowerCase();
let geo = {};

function status(message, type='loading') { const el=document.getElementById('rv-status'); el.className=`rv-status ${type}`; el.textContent=message; }
async function call(action, data=null, method='GET') { const url=method==='GET'?`${API}?${new URLSearchParams({acao:action,...(data||{})})}`:`${API}?acao=${encodeURIComponent(action)}`; try{const r=await fetch(url,{method,headers:method==='POST'?{'Content-Type':'application/json'}:{},body:method==='POST'?JSON.stringify(data||{}):null});const t=await r.text();return t?JSON.parse(t):{sucesso:false,mensagem:'Resposta vazia.'};}catch(e){console.error('[RondaCheckin]',e);return{sucesso:false,mensagem:'Não foi possível comunicar com a central de rondas.'};}}
function solicitarLocalizacao(){if(!navigator.geolocation)return; navigator.geolocation.getCurrentPosition((p)=>{geo={latitude:p.coords.latitude,longitude:p.coords.longitude,precisao_metros:p.coords.accuracy};},()=>{}, {enableHighAccuracy:true,timeout:8000,maximumAge:60000});}
async function iniciar(){if(!/^[a-f0-9]{64}$/.test(token)){status('QR Code inválido. Solicite uma nova etiqueta ao administrador.','error');return;}solicitarLocalizacao();const r=await call('qr_detalhe',{token});if(!r.sucesso){status(r.mensagem||'Ponto QR indisponível.','error');return;}const d=r.dados;document.getElementById('rv-ponto-nome').textContent=d.ponto_nome||'Ponto de ronda';document.getElementById('rv-rota-nome').textContent=d.rota_nome||'';document.getElementById('rv-condominio').textContent=d.condominio||'—';document.getElementById('rv-local').textContent=d.localizacao||'Não informado';document.getElementById('rv-instrucoes').textContent=d.instrucoes||'Sem instruções adicionais.';const sel=document.getElementById('rv-vigilante');sel.innerHTML='<option value="">Selecione seu nome</option>'+(d.vigilantes||[]).map((v)=>`<option value="${Number(v.id)}">${String(v.nome).replace(/[&<>]/g,'')}</option>`).join('');document.getElementById('rv-ponto-card').classList.remove('rv-hidden');document.getElementById('rv-checkin-form').classList.remove('rv-hidden');status('Ponto validado. Informe o vigilante para confirmar a passagem.','success');}
document.getElementById('rv-checkin-form').addEventListener('submit',async(e)=>{e.preventDefault();const b=document.getElementById('rv-submit');const colaboradorId=Number(document.getElementById('rv-vigilante').value);if(!colaboradorId){status('Selecione o vigilante responsável.','error');return;}b.disabled=true;status('Registrando passagem da ronda...','loading');const r=await call('registrar_leitura',{token,colaborador_id:colaboradorId,...geo},'POST');if(!r.sucesso){status(r.mensagem||'Não foi possível registrar a leitura.','error');b.disabled=false;return;}status(`${r.mensagem}${r.dados?.atraso_minutos?` Atraso: ${r.dados.atraso_minutos} min.`:''}`,'success');b.textContent='Passagem registrada';document.getElementById('rv-vigilante').disabled=true;});
iniciar();
