-- PRÉVIA SOMENTE LEITURA — RECONSTRUÇÃO DO TENANT 1
-- Exige os bancos inlaud99_erpserra e inlaud99_erpcondor no mesmo servidor.
DROP PROCEDURE IF EXISTS `inlaud99_erpcondor`.`mt_previa_tabela`;
CREATE TEMPORARY TABLE IF NOT EXISTS mt_previa_reconstrucao(
  tabela VARCHAR(128) NOT NULL, origem BIGINT NOT NULL, destino_atual BIGINT NOT NULL, excesso BIGINT NOT NULL
) ENGINE=Memory;
TRUNCATE TABLE mt_previa_reconstrucao;
DELIMITER $$
CREATE PROCEDURE `inlaud99_erpcondor`.`mt_previa_tabela`(IN p_tabela VARCHAR(128))
BEGIN
  DECLARE v_tem_tenant INT DEFAULT 0;
  SELECT COUNT(*) INTO v_tem_tenant FROM INFORMATION_SCHEMA.COLUMNS
   WHERE BINARY TABLE_SCHEMA=BINARY 'inlaud99_erpcondor' AND BINARY TABLE_NAME=BINARY p_tabela AND BINARY COLUMN_NAME=BINARY 'tenant_id';
  SET @q=CONCAT('SELECT COUNT(*) INTO @orig FROM `inlaud99_erpserra`.`',p_tabela,'`'); PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;
  IF v_tem_tenant>0 THEN SET @q=CONCAT('SELECT COUNT(*) INTO @dest FROM `inlaud99_erpcondor`.`',p_tabela,'` WHERE tenant_id=1');
  ELSE SET @q=CONCAT('SELECT COUNT(*) INTO @dest FROM `inlaud99_erpcondor`.`',p_tabela,'`'); END IF;
  PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;
  INSERT INTO mt_previa_reconstrucao VALUES(p_tabela,COALESCE(@orig,0),COALESCE(@dest,0),GREATEST(0,COALESCE(@dest,0)-COALESCE(@orig,0)));
END$$
DELIMITER ;
CALL mt_previa_tabela('abastecimento_lancamentos');
CALL mt_previa_tabela('abastecimento_recargas');
CALL mt_previa_tabela('abastecimento_saldo');
CALL mt_previa_tabela('abastecimento_veiculos');
CALL mt_previa_tabela('acessos_visitantes');
CALL mt_previa_tabela('alertas_estoque');
CALL mt_previa_tabela('avaliacoes');
CALL mt_previa_tabela('avaliacoes_backup');
CALL mt_previa_tabela('bridge_eventos_log');
CALL mt_previa_tabela('bridge_status');
CALL mt_previa_tabela('categorias_estoque');
CALL mt_previa_tabela('checklist_alertas_config');
CALL mt_previa_tabela('checklist_alertas_gerados');
CALL mt_previa_tabela('checklist_itens');
CALL mt_previa_tabela('checklist_km_acumulado');
CALL mt_previa_tabela('checklist_veicular');
CALL mt_previa_tabela('conciliacoes');
CALL mt_previa_tabela('config_periodo_leitura');
CALL mt_previa_tabela('configuracao_smtp');
CALL mt_previa_tabela('configuracoes');
CALL mt_previa_tabela('contas_bancarias');
CALL mt_previa_tabela('contas_pagar');
CALL mt_previa_tabela('contas_receber');
CALL mt_previa_tabela('contrato_aditivos');
CALL mt_previa_tabela('contrato_documentos');
CALL mt_previa_tabela('contrato_orcamento_documentos');
CALL mt_previa_tabela('contrato_orcamentos');
CALL mt_previa_tabela('contratos');
CALL mt_previa_tabela('controlid_dispositivos');
CALL mt_previa_tabela('controlid_eventos_acesso');
CALL mt_previa_tabela('controlid_push_eventos');
CALL mt_previa_tabela('crm_anexos');
CALL mt_previa_tabela('crm_interacoes');
CALL mt_previa_tabela('crm_relacionamentos');
CALL mt_previa_tabela('crm_sequencia');
CALL mt_previa_tabela('departamentos');
CALL mt_previa_tabela('dependentes');
CALL mt_previa_tabela('dispositivos_console');
CALL mt_previa_tabela('dispositivos_controlid');
CALL mt_previa_tabela('dispositivos_controlid_leituras');
CALL mt_previa_tabela('dispositivos_controlid_sync_log');
CALL mt_previa_tabela('dispositivos_seguranca');
CALL mt_previa_tabela('dispositivos_tablets');
CALL mt_previa_tabela('documentos');
CALL mt_previa_tabela('documentos_acessos');
CALL mt_previa_tabela('documentos_compartilhamentos');
CALL mt_previa_tabela('documentos_departamentos_migrado_bkp');
CALL mt_previa_tabela('documentos_grupos');
CALL mt_previa_tabela('documentos_grupos_moradores');
CALL mt_previa_tabela('documentos_grupos_usuarios');
CALL mt_previa_tabela('documentos_logs');
CALL mt_previa_tabela('documentos_pastas');
CALL mt_previa_tabela('documentos_tipos');
CALL mt_previa_tabela('documentos_usuarios_acesso');
CALL mt_previa_tabela('email_alertas');
CALL mt_previa_tabela('email_delivery_logs');
CALL mt_previa_tabela('email_log');
CALL mt_previa_tabela('email_providers');
CALL mt_previa_tabela('email_templates');
CALL mt_previa_tabela('empresa');
CALL mt_previa_tabela('empresa_log');
CALL mt_previa_tabela('face_descriptors');
CALL mt_previa_tabela('fornecedores');
CALL mt_previa_tabela('grupos_inventario');
CALL mt_previa_tabela('hidrometro');
CALL mt_previa_tabela('hidrometros');
CALL mt_previa_tabela('hidrometros_historico');
CALL mt_previa_tabela('historico_importacoes_ofx');
CALL mt_previa_tabela('historico_pagamentos');
CALL mt_previa_tabela('historico_status_pedido');
CALL mt_previa_tabela('importacoes_financeiras');
CALL mt_previa_tabela('importacoes_financeiras_itens');
CALL mt_previa_tabela('inventario');
CALL mt_previa_tabela('lancamentos_agua');
CALL mt_previa_tabela('leituras');
CALL mt_previa_tabela('leituras_fotos');
CALL mt_previa_tabela('local_acessos');
CALL mt_previa_tabela('local_acessos_log');
CALL mt_previa_tabela('local_acessos_tipos');
CALL mt_previa_tabela('log_reset_senha');
CALL mt_previa_tabela('logs_acesso_qrcode');
CALL mt_previa_tabela('logs_erro');
CALL mt_previa_tabela('logs_financeiro');
CALL mt_previa_tabela('logs_sistema');
CALL mt_previa_tabela('logs_validacoes_dispositivo');
CALL mt_previa_tabela('manual_artigos');
CALL mt_previa_tabela('manual_avaliacoes');
CALL mt_previa_tabela('manual_buscas');
CALL mt_previa_tabela('manual_categorias');
CALL mt_previa_tabela('manual_favoritos');
CALL mt_previa_tabela('manual_historico');
CALL mt_previa_tabela('manual_modulos');
CALL mt_previa_tabela('marcas_dispositivo');
CALL mt_previa_tabela('media_avaliacoes_fornecedor');
CALL mt_previa_tabela('media_avaliacoes_produto');
CALL mt_previa_tabela('modelos_dispositivo');
CALL mt_previa_tabela('moradores');
CALL mt_previa_tabela('movimentacoes_bancarias');
CALL mt_previa_tabela('movimentacoes_estoque');
CALL mt_previa_tabela('notif_alertas');
CALL mt_previa_tabela('notif_destinatarios');
CALL mt_previa_tabela('notif_regras');
CALL mt_previa_tabela('notificacoes');
CALL mt_previa_tabela('notificacoes_downloads');
CALL mt_previa_tabela('notificacoes_visualizacoes');
CALL mt_previa_tabela('os_assuntos');
CALL mt_previa_tabela('os_chamados');
CALL mt_previa_tabela('os_config_homem_hora');
CALL mt_previa_tabela('os_etapas');
CALL mt_previa_tabela('os_interacao_fotos');
CALL mt_previa_tabela('os_interacoes');
CALL mt_previa_tabela('os_materiais_usados');
CALL mt_previa_tabela('os_recursos_humanos');
CALL mt_previa_tabela('pedidos');
CALL mt_previa_tabela('planos_contas');
CALL mt_previa_tabela('produtos_estoque');
CALL mt_previa_tabela('produtos_servicos');
CALL mt_previa_tabela('protocolos');
CALL mt_previa_tabela('pwa_configuracoes');
CALL mt_previa_tabela('pwa_logs');
CALL mt_previa_tabela('pwa_notificacoes_push');
CALL mt_previa_tabela('pwa_notificacoes_recebidas');
CALL mt_previa_tabela('pwa_versao');
CALL mt_previa_tabela('ramos_atividade');
CALL mt_previa_tabela('recebedores');
CALL mt_previa_tabela('registros_acesso');
CALL mt_previa_tabela('rh_banco_horas');
CALL mt_previa_tabela('rh_colaboradores');
CALL mt_previa_tabela('rh_escala');
CALL mt_previa_tabela('rh_ponto_lancamento');
CALL mt_previa_tabela('rh_ponto_periodo');
CALL mt_previa_tabela('tipos_dispositivo');
CALL mt_previa_tabela('unidades');
CALL mt_previa_tabela('usuario_modulos');
CALL mt_previa_tabela('validacoes_acesso');
CALL mt_previa_tabela('validacoes_face_id');
CALL mt_previa_tabela('veiculos');
CALL mt_previa_tabela('visitantes');
DROP PROCEDURE `inlaud99_erpcondor`.`mt_previa_tabela`;
SELECT tabela,origem,destino_atual,excesso FROM mt_previa_reconstrucao WHERE excesso>0 ORDER BY excesso DESC,tabela;
SELECT SUM(origem) AS registros_origem,SUM(destino_atual) AS registros_destino_atual,SUM(excesso) AS excesso_estimado FROM mt_previa_reconstrucao;
